### ISSUE TITLE
add translations

### ISSUE THREAD

**Issue by wamserma** [wamserma/tex-tdl#1]
1. clone/fork the repo
2. duplicate a file in `strings`
3. rename to your desired locale
4. edit the strings
5. add your locale to the env: section in `.travis.yml`
6. send a pull request

**Comment by amritsinghcse** [comment]
Doing for fr-FR and es-ES.

**Comment by FleetAdmiral** [comment]
Doing it for hi-IN and ja-JP. @wamserma Do i stick to English script/wx notation or can i use native scripts for each language?

**Comment by andyps** [comment]
Hi! I've added ukrainian and russian translations https://github.com/wamserma/tex-tdl/pull/4

**Comment by ghost** [comment]
Hiya
I added a Dutch translation (PR #8 )
Happy Hacktoberfest!

**Comment by wamserma** [comment]
@FleetAdmiral Please stick to English notation and just translate/rephrase the parts in curly braces.

@all thanks for the awesome feedback! Will work through the PRs in the next days.

**Comment by codegateau** [comment]
Doing for ms-MY . Check it out
